### PR TITLE
Add :PRINT-CASE argument to quickload, set :UPCASE by default

### PR DESCRIPTION
**Pull request by jessymilare**
Some systems don't load correctly when `*PRINT-CASE*` isn't `:UPCASE`.

### CODE REVIEW

**Comment by quicklisp** [comment]
This is really interesting! What systems are affected and how did you find
out?

**Comment by jessymilare** [comment]
I found it out because I don't like a REPL that looks like it is screaming lol. So I set *print-case* to :downcase, which makes SLIME command <M-.> stop working because it looks for symbols with downcased names.

**Comment by quicklisp** [comment]
Thanks for the context. I'm hesitant to add this because there are likely a bunch of other variables that would affect things in a similar way. The first one that comes to mind is `*read-default-float-format*`. The most consistent way to handle all of them is let-binding the special around quickload (or any other operation). Should they all be rolled into quickload's lambda list?

**Comment by quicklisp** [comment]
Also, style-wise, I'd prefer something like this: `&key ... ((:print-case *print-case*) *print-case*) ...`

**Comment by jessymilare** [comment]
I don't see any problem including some (maybe many) specials into quickload's lambda list. Some standard functions (e.g. `write') and some libraries (e.g. bordeaux-threads) do that. If you wrap the special around `quickload', the user loses control.

I'll change the style.

**Comment by quicklisp** [comment]
>  If you wrap the special around quickload, the user loses control.

I don't understand - how is `(let ((*print-case* :upcase)) (ql:quickload ...))` reducing user control?

**Comment by jessymilare** [comment]
> > If you wrap the special around quickload, the user loses control.
> 
> I don't understand - how is `(let ((*print-case* :upcase)) (ql:quickload ...))` reducing user control?

If the user has to type that, that is a lot to type and doesn't integrate well with SLIME, LEM editor, etc. IMHO, the default way of calling the function should work as-is.

**Comment by quicklisp** [comment]
Ahh, thanks, I see the argument. Despite the clearly written title and clear code, I misinterpreted this as providing an argument to bind the special variable without changing it on the way in.

Now that I understand, I'm not comfortable changing `*print-case*` by default via quickload. Things that break with a non-default `*print-case*` should be fixed or let-binding should be used instead.

**Pull request closed without merging**
